# Generated by Django 5.0.1 on 2024-03-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('standart', 'Standard'), ('bootcamp', 'Bootcamp'), ('online', 'Online')], default='s', max_length=15),
        ),
    ]
