# Generated by Django 5.0.1 on 2024-03-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard'), ('bootcamp', 'Bootcamp'), ('online', 'Online')], default='s', max_length=15),
        ),
    ]
