# Generated by Django 5.0.1 on 2024-03-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='category',
        ),
    ]
