# Generated by Django 5.0.1 on 2024-03-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=156)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=155)),
                ('location', models.CharField(max_length=156)),
                ('image', models.ImageField(upload_to='posts/')),
            ],
        ),
    ]
